name: Update KoboToolbox Data

on:
  schedule:
    # Run on the 1st day of every month at 6 AM UTC
    - cron: '0 6 1 * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest data from KoboToolbox
        env:
          KOBO_TOKEN: ${{ secrets.KOBO_TOKEN }}
        run: |
          echo "🔄 Monthly data update from KoboToolbox..."
          
          curl -H "Authorization: Token $KOBO_TOKEN" \
               "https://kf.kobotoolbox.org/api/v2/assets/aPhcaneoEuEZLLQbroHu6C/data.json" \
               -o data.json

      - name: Commit and push if data changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "ℹ️ No changes to commit"
          else
            git commit -m "📅 Monthly data update from KoboToolbox $(date '+%Y-%m-%d')"
            git push
            echo "✅ Monthly data update completed"
          fi
